# Generated by Django 3.2 on 2021-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.IntegerField(default=0),
        ),
    ]
