# Generated by Django 3.2 on 2021-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Viewed'), (2, 'Accepted'), (3, 'Rejected')]),
        ),
    ]
