# Generated by Django 3.2 on 2021-04-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zoom_auth_token',
            field=models.TextField(default=''),
        ),
    ]
