# Generated by Django 3.2 on 2021-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_zoom_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zoom_refresh_token',
            field=models.TextField(default=''),
        ),
    ]
