# Generated by Django 3.2 on 2021-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_zoom_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
