# Generated by Django 3.2 on 2021-04-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20210423_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='Job_id',
            new_name='job_id',
        ),
    ]
